### ISSUE TITLE
А если не нужен Breakpoint?

### ISSUE THREAD

**Issue by Ocupuc123** [SineYlo/transfer-elements#1]
Почему не предусмотрена опция, когда мне не нужен какой либо breakpoints, мне нужен трансфер здесь и сейчас)

**Comment by SineYlo** [comment]
@Ocupuc123 

В самой первой тестовой реализации библиотеки была такая возможность, но я решил её убрать, ибо посчитал, что она не имеет смысла, так как можно изначально в разметке указать блок там, где нужно. Привидите пример, для которого требуется данный функционал.
